Display an error message to the user if the file is too large to be loaded
applandinc/appmap-intellij-plugin pull request #71
Opened 2022-01-17 11:36 UTC by jansorg

Closes #70 
This PR adds the needed changes to display an error message for too large files instead of trying to load the content.
The file size limit is user-configurable and defaults to 20 megabytes.

Although it's technically possible to load the complete content instead of the truncated content, this isn't working well with the current implementation.
Currently, the file content is turned into a JS method call string taking the complete content as argument. For large files this and the needed JSON escaping of the content make things memory hungry and slow.
A method call is needed because the JS application is living in a sandboxed environment, which doesn't have access to `file://` URLs.

Possible workaround, which needs more investigation and more time than this PR: Add a custom scheme or resource URL handler and then instruct the JS application to load a file with our own custom protocol. The initial investigation of this turned out to be difficult, because custom scheme handlers must be added to the global JBCEF application before creating the first client. This isn't entirely under own control.
Additionally, we'd have to be very careful to not allow file system access for non-appmap files residing on the local filesystem.

![Screenshot_20220117_122835](https://user-images.githubusercontent.com/11473063/149762730-a2cdee4c-10b8-4fb8-8ab7-7bacf965160a.png)

2022-01-17 21:13 UTC, apotterri commented
> The file size limit is user-configurable as a global, application-wide value within the IDE and defaults to 20 megabytes. Only advanced users of the IDE would customize this.

Is the file size limit really user-configurable? I don't see any way to do it....

2022-01-17 21:16 UTC, apotterri requested changes
If the file-size limit is configurable, this PR needs some documentation describing how to change it. If it's not configurable, then things are fine as-is.

Also, how do updated versions get deployed to the JetBrains marketplace? Was Petr doing that?

2022-01-18 17:03 UTC, jansorg commented
@apotterri The file size is configurable, but only in a very technical way. See https://www.jetbrains.com/help/idea/tuning-the-ide.html#common-platform-properties for instructions. I wouldn't advertise this to users because it's something 99% of users won't do and it also side-effects for every other file in the IDE.
Petr was uploading new plugins to https://plugins.jetbrains.com/plugin/16701-appmap, based on the instructions at https://github.com/applandinc/appmap-intellij-plugin#releases. Please let me know if you need help with it.

You're already member https://plugins.jetbrains.com/organizations/AppLand, if you don't have upload permissions yet the other members should be able to grant you the needed permissions.

2022-01-19 11:25 UTC, apotterri commented
> @apotterri The file size is configurable, but only in a very technical way. See https://www.jetbrains.com/help/idea/tuning-the-ide.html#common-platform-properties for instructions. I wouldn't advertise this to users because it's something 99% of users won't do and it also has side-effects for every other file in the IDE.
> 
> Petr was uploading new plugins to https://plugins.jetbrains.com/plugin/16701-appmap, based on the instructions at https://github.com/applandinc/appmap-intellij-plugin#releases. Please let me know if you need help with it.
> 
> You're already member https://plugins.jetbrains.com/organizations/AppLand, if you don't have upload permissions yet the other members should be able to grant you the needed permissions.

Thanks for the info about configuring the file size. I agree that we don't need to tell users about this, unless they ask.

I don't see any way for me to upload a new version of the plugin, so I'm assuming I don't yet have permission to do it. I'll work with others to get me going.

It looks to me like we should be able to automate upload of new versions, using the Gradle plugin: https://plugins.jetbrains.com/docs/intellij/deployment.html . Do you know of any reason this wouldn't work?

2022-01-19 11:25 UTC, apotterri approved these changes

2022-01-19 11:25 UTC, merged

2022-01-19 11:42 UTC, jansorg commented
@apotterri Sure, automatic uploads are possible, e.g. with GitHub actions. I offered to work on CI, but this task never made it onto the lists of things to work on.

2022-01-19 12:15 UTC, apotterri commented
Great, thanks for confirming that.